# Generated by Django 5.0.6 on 2024-08-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_categoryoffer_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.FloatField(),
        ),
    ]
